import html2canvas from 'html2canvas';

export interface IdCardDownloadOptions {
  cardRef: React.RefObject<HTMLDivElement | null>;
  fileName: string;
  onDownloadStart?: () => void;
  onDownloadComplete?: () => void;
  onDownloadError?: (error: Error) => void;
}

// ── Backend PDF Download (Puppeteer-generated, print-ready A6) ──

export interface PdfDownloadOptions {
  memberId: string;
  onDownloadStart?: () => void;
  onDownloadComplete?: () => void;
  onDownloadError?: (error: Error) => void;
}

/**
 * Downloads a press-ready A6 PDF generated by the backend
 * (Node.js + Puppeteer) for the given member ID.
 *
 * Endpoint: GET /api/id-card/download/:memberId
 * Requires: Bearer token in localStorage
 */
export const downloadIdCardPdf = async ({
  memberId,
  onDownloadStart,
  onDownloadComplete,
  onDownloadError,
}: PdfDownloadOptions): Promise<void> => {
  try {
    onDownloadStart?.();

    const token = localStorage.getItem('token');
    if (!token) throw new Error('No authentication token found. Please log in again.');

    // VITE_API_URL already includes /api (e.g. http://localhost:5003/api)
    const apiBase = (import.meta.env.VITE_API_URL || 'http://localhost:5003/api').replace(/\/+$/, '');
    const response = await fetch(`${apiBase}/id-card/download/${encodeURIComponent(memberId)}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!response.ok) {
      let message = `Server error (${response.status})`;
      try {
        const json = await response.json();
        message = json.message || message;
      } catch {}
      throw new Error(message);
    }

    // Extract filename from Content-Disposition header
    const disposition = response.headers.get('Content-Disposition') || '';
    const fileNameMatch = disposition.match(/filename="?([^";\n]+)"?/);
    const fileName = fileNameMatch ? fileNameMatch[1] : `${memberId}-VARA-ID.pdf`;

    const blob = await response.blob();
    const url  = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href     = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    onDownloadComplete?.();
  } catch (error) {
    const err = error instanceof Error ? error : new Error('PDF download failed');
    console.error('[IDCard] PDF download error:', err.message);
    onDownloadError?.(err);
  }
};

/**
 * Download ID card as high-quality PNG
 * A6 size: 105mm x 148mm at 300 DPI = 1240px x 1748px
 */
export const downloadIdCard = async ({
  cardRef,
  fileName,
  onDownloadStart,
  onDownloadComplete,
  onDownloadError,
}: IdCardDownloadOptions): Promise<void> => {
  if (!cardRef.current) {
    const error = new Error('Card reference not found');
    onDownloadError?.(error);
    return;
  }

  try {
    onDownloadStart?.();

    // A6 dimensions at 300 DPI for print quality
    const A6_WIDTH_300DPI = 1240;
    const A6_HEIGHT_300DPI = 1748;

    // Capture the card element at high resolution
    const canvas = await html2canvas(cardRef.current, {
      scale: 3, // Higher scale for better quality
      useCORS: true,
      allowTaint: false,
      backgroundColor: '#0066FF',
      logging: false,
      width: cardRef.current.offsetWidth,
      height: cardRef.current.offsetHeight,
    });

    // Create a new canvas with exact A6 dimensions at 300 DPI
    const finalCanvas = document.createElement('canvas');
    finalCanvas.width = A6_WIDTH_300DPI;
    finalCanvas.height = A6_HEIGHT_300DPI;

    const ctx = finalCanvas.getContext('2d');
    if (!ctx) {
      throw new Error('Could not get canvas context');
    }

    // Fill with background color
    ctx.fillStyle = '#0066FF';
    ctx.fillRect(0, 0, A6_WIDTH_300DPI, A6_HEIGHT_300DPI);

    // Draw the captured image scaled to fit A6 dimensions
    ctx.drawImage(canvas, 0, 0, A6_WIDTH_300DPI, A6_HEIGHT_300DPI);

    // Convert to blob and download
    finalCanvas.toBlob(
      (blob) => {
        if (!blob) {
          throw new Error('Failed to create image blob');
        }

        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${fileName}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);

        onDownloadComplete?.();
      },
      'image/png',
      1.0 // Maximum quality
    );
  } catch (error) {
    const err = error instanceof Error ? error : new Error('Download failed');
    console.error('Error downloading ID card:', err);
    onDownloadError?.(err);
  }
};
